### ISSUE TITLE
BitBucket Server 6.3.5 external hook 7.3.0 and 7.5.0 stopped working

### ISSUE THREAD

**Issue by azhou2000** [reconquest/atlassian-external-hooks#102]
We have BitBucket Server 6.3.5 with external hook enabled in some of the repositories to run a shell script located at <bitbucket-home-dir>/external-hooks/.  The shell script is to evaluate each commit push and reject the commit if certain conditions are not met and echo a message to users who make the push.  It used to work great and we can determine various of conditions as out development rules.

Now for some reason, with external-hook 7.3.0 and 7.5.0 does not execute anymore.  Each time there is a push, there is no echoing message and under whatever conditions, BitBucket just accepts the push, and we got a atlassian-bitbucket.log entry as:

`2019-11-07 14:51:47,700 WARN  [http-nio-7990-exec-8] zhouan@nih.gov @19PSRRMx891x371x0 10.157.117.172,165.112.229.7 "POST /scm/<proj>/<repo>.git/git-receive-pack HTTP/1.1" c.a.s.i.s.g.p.http.HttpReceivePack DBOLTP/oltp_acrpt[792]: Git hooks have not been called. Please verify that the hooks are configured correctly - see https://confluence.atlassian.com/display/BITBUCKETSERVERKB/Git+hook+scripts+are+not+executing?utm_campaign=in-app-help&utm_medium=in-app-help&utm_source=stash for details`

The URL provided does not seem to be related with BitBucket external-hook, rather the general git hook.

I've tried both external-hook 7.3.0 and 7.5.0 and got the same effect.  We are paying customer of BitBucket external-hook for some important feature here.  Please let me know what can we do to fix the issue. 

Thanks in advance.

**Comment by bturner** [comment]
@azhou2000,

I'm one of the Bitbucket Server developers. External hooks for this app are triggered by Bitbucket Server itself, as part of its normal hook operations. That means if Bitbucket Server is not triggering hooks, any scripts you've configured via this app will also not be triggered.

I'd recommend you open a support case with Atlassian at https://support.atlassian.com/contact so one of our support engineers can work with you to determine why Bitbucket Server's hooks aren't being triggered.

Best regards,
Bryan Turner
Atlassian Bitbucket

**Comment by seletskiy** [comment]
@azhou2000 Hello!

I'm part of the External Hooks plugin team.
As @bturner mentioned, it seems that your Bitbucket instance is not configured correctly, so any hooks enabled via our plugin will not work.

It is best to contact Atlassian support for this case, since problem is out of scope for our team to resolve it efficiently.

**Comment by azhou2000** [comment]
Thanks Stainslav and Bryan.  I think I figured out the reason.  I'm trying different conditions of the hook script and like to test it in our BitBucket dev environment.  At the same time, we are migrating BitBucket to Data Center solution, and also with BitBucket dev for a practice.  It's likely our BitBucket dev Data Center is not configured correctly, so the hook script is not recognized at all.

Again, thanks a lot for the help.
