### ISSUE TITLE
Free or commercial?

### ISSUE THREAD

**Issue by Marakai** [reconquest/atlassian-external-hooks#108]
Hi!

We found that the addon works well with our requirement to mirror Bitbucket DC to AWS CodeCommit. Wanting to do the right thing and having downloaded the addon from the Atlassian Marketplace, we thought we'd have to buy licenses.

Yes, here we now see if licensed under GPL with the source available.

We're slightly confused!

**Comment by seletskiy** [comment]
@Marakai Hi!

We're same people who release add-on on the Atlassian Marketplace.

While source code is available for free here to everyone for inspection, we're offering support only for the customers who install add-on either from the Marketplace or who receive prebuilt versions directly from us via support channels.

Please ping us directly at [we@reconquest.io](mailto:we@reconquest.io) so we can issue your company a discount on the license purchase.

**Comment by Marakai** [comment]
Thanks for that! Policy is to use supported software in production, so we would indeed want to buy licenses. I will pass that on!
