### ISSUE TITLE
Project level hooks not triggering with inheritance on at first commit/push

### ISSUE THREAD

**Issue by Marakai** [reconquest/atlassian-external-hooks#109]
### Issue: 

When creating a new repository in Bitbucket with Hooks set at the Project level (both pre- and post-receive), the first commit/push to the repository will not trigger the hooks.

Hooks are set to Inherited (Enabled) at the repo level. When changing the setting to Enable instead of Inherit, then a first time push will trigger the hook.

Any further commit/pushes will trigger the Project level hooks correctly - it's only the first one.

### What should happen: 

The Project-level hooks should trigger no matter what, if set to Inherited (Enabled).

### Work-around:

If, at creation of repo, you go into Settings, then toggle the repo-level Hook from Inherited (Enabled) to Enabled, Save that settings *and then immediately set it back to Inherited (Enabled)*, it will trigger correctly, though it's not immediately clear if it's because it now works properly - or whether it's actually now just continuing to use the repo-level hook and didn't actually switch back to Project-level. Would need to test with two different Hook scripts to verify.

**Comment by kovetskiy** [comment]
Hi,
Thanks for the bug report, we will try to reproduce it on our end today.
I'll keep you posted.

**Comment by kovetskiy** [comment]
We've reproduced the bug and applied the fix, we'll release the new version today.

**Comment by kovetskiy** [comment]
Heads up! The new version is available for upgrade through Atlassian Marketplace — 10.1.0

https://marketplace.atlassian.com/apps/1211631/external-hooks-by-reconquest/version-history#b6532

Thanks for the bug report!
