### ISSUE TITLE
Unable to Set Global Hooks on a Postges-backed Bitbucket Server

### ISSUE THREAD

**Issue by briankohler** [reconquest/atlassian-external-hooks#125]
On a fresh installation on latest BitBucket server, the tables are created with UPPERCASE column names.  There is at least one place in the code where raw SQL is run against the DB (not using the ORM) and the column name is not capitalized.  If running PostgreSQL, this results in the Global Hooks page spinning indefinitely, and stack traces in the bitbucket app logs indicated "column "hook" does not exist for table.."

**Comment by briankohler** [comment]
https://github.com/reconquest/atlassian-external-hooks/blob/9aca31fca5235b37a93cd3a68071b15a1dde7815/src/main/java/com/ngs/stash/externalhooks/dao/GlobalHookSettingsDao.java#L31

**Comment by kovetskiy** [comment]
Closing since this is fixed.
