### ISSUE TITLE
Plugin not compatible with Bitbucket 8

### ISSUE THREAD

**Issue by mikednk** [reconquest/atlassian-external-hooks#130]
Hi Team,
Do you plan a new release for Bitbucket 8?
Best regards,
Mike

**Comment by kovetskiy** [comment]
@mikednk Hey! Yes, we do, we don't only plan, we already test the new version on new version of Bitbucket. We are expecting to release it this week.

Do you use [mesh servers](https://ja.confluence.atlassian.com/bitbucketserver080/bitbucket-mesh-1115143197.html) for your Bitbucket 8 installation?

**Comment by mikednk** [comment]
Hi @kovetskiy, this is awesome! thank you for your reply. We do not use mesh servers.

**Comment by mikednk** [comment]
Hi @kovetskiy, do you have any news concerning the release for Bitbucket 8?

**Comment by kovetskiy** [comment]
@mikednk hey, please give a try to the new version of the add-on — 13.0.0

https://marketplace.atlassian.com/apps/1211631/external-hooks-by-reconquest/version-history#b6772

**Comment by mikednk** [comment]
I will! thanks @kovetskiy

**Comment by kovetskiy** [comment]
Closing since this is fixed.
