### ISSUE TITLE
External Hooks plugin not supported at Bitbucket 8

### ISSUE THREAD

**Issue by gsobel** [reconquest/atlassian-external-hooks#131]
Hello,
We would like to upgrade our Bitbucket to 8.2.2
We’ve understood External Hooks plugin is currently not supported bitbucket 8 release.
Could you please advise?
Best Regards,

**Comment by kovetskiy** [comment]
Hey,

We are currently finishing the implementation of compatibility with the new Bitbucket version and expecting it to release within a week.

Are you using Mesh for Bitbucket?

Thanks

**Comment by gsobel** [comment]
Hi,

Thanks for the update.
No, we're not using mesh, we're using Bitbucket server.
Is the update will be available also for the server version? 

Thanks and regards

**Comment by kovetskiy** [comment]
> Is the update will be available also for the server version?

Sure, we will do everything we can to make it compatible with BB Server.

**Comment by kovetskiy** [comment]
Please give a try to the new version of the add-on — 13.0.0

https://marketplace.atlassian.com/apps/1211631/external-hooks-by-reconquest/version-history#b6782

**Comment by kovetskiy** [comment]
Closing since this is fixed.
