### ISSUE TITLE
Error 500 on external-hooks/diagnostics page 

### ISSUE THREAD

**Issue by elementaryx** [reconquest/atlassian-external-hooks#133]
Recently I've upgraded the hooks plugin on my Bitbucket Server 7.17.10 LTS version. I was using plugin version 12.0.1 and everything was working fine but after upgrading to version 13.0.0, the external-hooks/diagnostics page started returning Error 500. I've checked the logs and it shows "ERROR [http-nio-7990-exec-10] o.a.c.c.C.[.[.[/].[plugins] Servlet.service() for servlet [plugins] in context with path [] threw exception
java.lang.ClassCastException: ch.qos.logback.classic.Logger cannot be cast to ch.qos.logback.classic.Logger"

**Comment by seletskiy** [comment]
Thanks for the report, we're investigating the issue right now.

**Comment by seletskiy** [comment]
@elementaryx Hello, can you try latest 13.1.0 External Hooks release?

**Comment by kovetskiy** [comment]
Closing since fixed
