### ISSUE TITLE
Updating plugin to 13.1.2 does not work.

### ISSUE THREAD

**Issue by eugenetan** [reconquest/atlassian-external-hooks#147]
After updating to the LTS 8.19.6 and updating the plugin 13.1.2, the plugin does not work.

In a repo, I know the plugin is partially working when i deliberately mis-spell the script. And it complains that the script does not exist.

How when a script that exists is specified. That script is never executed.

**Comment by kovetskiy** [comment]
Hey, we are looking into the issue.

**Comment by kovetskiy** [comment]
```
Starting from Bitbucket Data Center 8.18, hook script support is disabled by default. However, you can enable the feature at any time.

If hook script support is an integral part of your workflow, we strongly recommend setting the relevant property to enable the feature prior to the upgrade.

To do this, in the bitbucket.properties file, set the property feature.hook.scripts=true. Then, restart Bitbucket for the changes to take effect. If you run a Bitbucket cluster, a rolling restart is enough to pick up the configuration properties you set to enable the features.
```

https://developer.atlassian.com/server/bitbucket/how-tos/register-maintain-hook-scripts/
