### ISSUE TITLE
Execute pre-receive hook during merge pull-request event 

### ISSUE THREAD

**Issue by val0** [reconquest/atlassian-external-hooks#19]
Could you please give me a hint how I can execute pre-receive hook during merge pull request occurs?

**Comment by rappazzo** [comment]
The external hooks plugin does not enable this out of the box.  You would have to fork this project and add that feature.  It's not too hard though:

Add your component to atlassian-plugin.xml:

    <component key="myMergeCheck" class="com.you.stash.MergePullRequestHook"/>

The `MergePullRequestHook` should implement `MergeRequestCheck`.  It would have to make some of the same calls that happen on the pre-receive from this plugin

**Comment by seletskiy** [comment]
@val0,  @rappazzo: Yeah, it's pending feature. I have other things to do right now, but, @val0, if you will implement it, I will be glad to receive PR.

**Comment by yorammi** [comment]
This would be great if this will be implemented!!!

**Comment by atikhono** [comment]
+1

**Comment by seletskiy** [comment]
Merge check is implemented in the #32.
