### ISSUE TITLE
Data center support

### ISSUE THREAD

**Issue by kumaran-codez** [reconquest/atlassian-external-hooks#31]
We were looking at using this addon to work on post hooks in bitbucket server. Is there a timeline to compile this code to support datacenter version of bitbucket ?

**Comment by robisonba** [comment]
Any update on this? Is the add-on supported in Bitbucket Data Center?

**Comment by seletskiy** [comment]
@robisonba, @kumaran-codez: I did not test it on the datacenter edition, however, I can enable plugin to be able to be downloaded on such instances. So, if you're ready to test it and provide some feedback, let me know.

**Comment by robisonba** [comment]
Yes. I can test it within the next week.

**Comment by itay** [comment]
FYI, we've been using the plugin for about a year and a half on a DC instance with 4 application nodes and hundreds of users. It's been working just fine.

The only thing to keep in mind is if your hook is doing some crazy things with files on disk or something like that, you have to keep in mind that you may be on NFS or might have multiple users, but nothing too concerning.

**Comment by seletskiy** [comment]
@itay: Can you provide little more insight? Are repositories sharded in some way across cluster, or you can reliably assume, that if post-receive hook had been launched, then you got full repository on the local node?

**Comment by seletskiy** [comment]
@robisonba: Data Center support version 3.3 released on marketplace, please, check it out.
