### ISSUE TITLE
HTML tags in messages

### ISSUE THREAD

**Issue by armsargis** [reconquest/atlassian-external-hooks#46]
Hi,

I am using external hook with BitBucket 4.10 and exiting with not 0 status with error message in stdout but I have html tags in messages. I guess code should be changed to avoid usages html tags in veto() call. Please check attachments. 

![screenshot from 2016-10-06 19-09-03](https://cloud.githubusercontent.com/assets/229335/19186644/49881e3a-8c98-11e6-81c4-1d62b248c457.png)
![screenshot from 2016-10-06 19-09-14](https://cloud.githubusercontent.com/assets/229335/19186643/4985ebec-8c98-11e6-848c-a4ec79134dc5.png)

Thanks.

**Comment by seletskiy** [comment]
Duplicates #43.
