### ISSUE TITLE
External Pre Receive Hook not run when Creating a branch via the Bitbucket UI

### ISSUE THREAD

**Issue by ghost** [reconquest/atlassian-external-hooks#54]
Hj 
We have a branching model where we want to ensure that our developers branches are namespaced i.e chris/<branch name> to enforce this we have written and  External Pre Receive Hook that is run we when our developers try to push to bitbucket  and the push is rejected if the do not confirm to our branching strategy.  

This is working fine if one works via a shell and the hook works fine but for som reason when one creates a branch the Bitbucket UI the External Pre Receive Hook is not run and the branch creation is not rejected. Is there a way one can get External Pre Receive Hook also to run when creating the branch via the UI alternatively do you have any thoughts of an alternative solution to implement this? 

We are using the 3.3-1 add-on of the external hooks and v4.14.3 of bitbucket

 Regards
Chris

**Comment by seletskiy** [comment]
This is fixed now.
