### ISSUE TITLE
Must be Stash Admin to configure external hook

### ISSUE THREAD

**Issue by duanecawthron** [reconquest/atlassian-external-hooks#6]
Hi, thanks for the hook. It's great. When I first started using it I could configure the hook as project Admin. Now, it will not let me configure the Executable and Positional Parameters of the External Post Receive Hook. It says, "You should be Stash Administrator to edit this field." Is that what you intended? It seems too restrictive to me.

**Comment by mjbros** [comment]
I seem to be able to add any script or executable as a repo admin. I thought that Stash Admin would mean a global role like Admin or System Admin.

**Comment by seletskiy** [comment]
@mjbros: you actually should be System Admin, not repo admin. You can specifiy executable only with [x] safe path option turned on.
