### ISSUE TITLE
Configure via API

### ISSUE THREAD

**Issue by ispyinternet** [reconquest/atlassian-external-hooks#62]
Would love to be able to set a hook using the bitbucket REST API endpoint. Any chance you can hook into this?

**Comment by dborisov** [comment]
Hey guys is there any plan to implement this soon? Manual hook configuration on 100+ repos is a big problem.

**Comment by kovetskiy** [comment]
@dborisov Hi! 

The hook can be turned on/off and configured using built-in Bitbucket REST API as any other hooks, but we have implemented a tool in a separated repository: https://github.com/reconquest/bitbucket-external-hook

Here is a simple example of how we enable & configure the pre-receive hook in a repository: https://github.com/reconquest/atlassian-external-hooks/blob/master/testutils/create-prereceive-hook

You might also be interested in https://github.com/kovetskiy/stacket

Sorry for forgetting to mention it here in the issue.

**Comment by dborisov** [comment]
@kovetskiy Great! Thanks man!
