### ISSUE TITLE
Can't configure the plugin on a project level

### ISSUE THREAD

**Issue by sdesmet** [reconquest/atlassian-external-hooks#63]
Hi,

Is it a deliberate choice that the hook can not be configured on a project level? I've got a lot of repositories and having to configure on each separately is a bit of a hassle.

![selection_947](https://user-images.githubusercontent.com/750318/35920335-09490e6e-0c31-11e8-9185-c2b0c70c6d15.png)

Thanks

**Comment by kovetskiy** [comment]
@sdesmet Hi, this feature is implemented, please check latest versions of the plugin in marketplace.
