### ISSUE TITLE
Unwanted HTML tags in Merge button pop-up

### ISSUE THREAD

**Issue by offmindby** [reconquest/atlassian-external-hooks#66]
Bitbucket Server 4.8.3
Using External Merge Check Hook for pull requests
Simply bash script checks some points and exit with code 1. Also some information is printed into standard output.
So, the Merge button is disabled as it should be and shows this output as a pop-up in brow
![screenshot from 2018-07-31 16-30-38]
ser. This pop-up contains some HTML tags which are added by Bitbucket, but couldn't be rendered by a browser.
I've checked Google Chrome 68.0.3440.84-1 and Firefox 
To reproduce:
- create a bash script which has any output and exit with code 1
- add this script as a hook for External Merge Check Hook
- create a pull request
- open a pull requests and click on a Merge button(which should be disabled)

(https://user-images.githubusercontent.com/5739685/43574231-5183276e-964c-11e8-925a-6c27106d0dad.png)

**Comment by seletskiy** [comment]
#46
