### ISSUE TITLE
Unable to merge changes: summaryMessage

### ISSUE THREAD

**Issue by kchawlaSP** [reconquest/atlassian-external-hooks#75]
I upgraded external hooks to 4.5-3 and I now see an error "summaryMessage" when trying to merge a change.  I am using bitbucket server 5.14.1

**Comment by kchawlaSP** [comment]
After downgrading back to 4.5-2, I am able to merge changes.

**Comment by kovetskiy** [comment]
@kchawlaSP Hi again, I have tested plugin version 4.5-3 on bitbucket version 5.14.1 and was not able to reproduce your problem, I have tested merge check hook that returns `exit 0` and `exit 1` (with message) and `exit 1` (without message). Everything was working as expected. 

Can you please help me to investigate this problem by providing steps to reproduce your problem? Also, can you send a screenshot of this "summaryMessage" error? Because I can't even find a place in the code where such error could happen (we have summaryMesssage variable, but I can't imagine in which case variable name can be transformed to an error message).

Thanks.

**Comment by kchawlaSP** [comment]
@kovetskiy, i just upgraded our production instance and I am seeing the issue there. I am actually seeing it on 4.5-2 now as well. It happens when I first open the PR. If I go ahead and add another commit to my branch, I am able to merge.  I am not sure exactly what is happening.

<img width="380" alt="screen shot 2018-11-15 at 7 31 43 am" src="https://user-images.githubusercontent.com/39931746/48563216-b09c8e80-e8a8-11e8-8503-d6d39c37fad6.png">

**Comment by kchawlaSP** [comment]
Editing the pull request title/description will get rid of the message.

**Comment by kchawlaSP** [comment]
I downgraded to 4.4-1 and everything seems to work.

**Comment by kovetskiy** [comment]
@kchawlaSP I believe I understand the nature of your problem now. 

The plugin doesn't run merge check hook on every page visit, the plugin runs merge check hook once for every pull-request update, stores the result in the database and shows it next time when you visit pull-request's page.

You can see this logic here:
https://github.com/reconquest/atlassian-external-hooks/blob/f2a1bbcf10fb77e069dd33e3bdfbf7f466a47c14/src/main/java/com/ngs/stash/externalhooks/hook/ExternalMergeCheckHook.java#L129-L156

There is only one explanation of "summaryMessage" error, some time ago you had a hook that was showing "summaryMessage" text message and now plugin remembers that state and shows this message for that version of pull-request.


As you said, editing the pull request itself in any way (title, description or commit) will update version (internal terminology) of pull request and merge check hook will be triggered again.

In 4.5-2 we just don't have this feature.

**Comment by kchawlaSP** [comment]
But that isn't the entire problem.  it shows summaryMessage, which is not coming from my merge check hook. Feel free to send me your hook and I can test it on my server.  

If there are additional logs I can send you, let me know how to do that as well.

**Comment by seletskiy** [comment]
@kchawlaSP: can you try to upgrade plugin to version 4.6-1? We introduced additional check here so merge check is called everytime underlying script changed.

**Comment by andrewkro** [comment]
@kovetskiy thanks for the details. 

we currently use the merge check to do custom work in JIRA, which updates over the life of the PR. so having it never check back and re-run the script has broken the workflow for us.

Would it be possible to make the caching result configurable so we can turn it off forcing merge to run on every page refresh (or set a custom TTL on the cache?)

Ill have to downgrade as well for the moment.

Thanks!

**Comment by kovetskiy** [comment]
@andrewkro Hello, yes, we are going to make this caching configurable. There is no ETA, but I will keep you posted.

**Comment by seletskiy** [comment]
Closed due architecture changes made in BB.
