### ISSUE TITLE
Datacenter support for version 5.16

### ISSUE THREAD

**Issue by agarwva2** [reconquest/atlassian-external-hooks#77]
We were looking at using this addon to work on pre and post hooks in bitbucket Data center verison 5.16. Is there a timeline to compile this code to support datacenter version of bitbucket ?

**Comment by seletskiy** [comment]
We are currently working on the DC support, but it's quite complicated process.

Do you mind scheduling a short call, we would like to learn which
exact setup of Bitbucket you have? For example, we need to know which
DB you use as backend since it's one of the requirements for DC
certification.

**Comment by seletskiy** [comment]
DC support is available now.
