### ISSUE TITLE
Unable to obtain a trial license to support Starter subscription

### ISSUE THREAD

**Issue by bdavy222** [reconquest/atlassian-external-hooks#84]
We (Duke Energy) are using a version of the external hooks plugin and require a plugin. We have a license for 1000, but I need a 10 starter license to work with a separate team behind a firewall. I can not load 1000 developer license with that. Can I get a license. This is going on a TEST system and then move to our production. The purchase of the 10 seat is in process.

thanks for your attention

**Comment by seletskiy** [comment]
@bdavy222 Please drop an e-mail to us on `we [at] reconquest.io`, we will try to issue a license for you.
