### ISSUE TITLE
Can't activate plugin for trial

### ISSUE THREAD

**Issue by PenelopeSam** [reconquest/atlassian-external-hooks#86]
Good Morning

I want to evaluate your plugin but i can't activate it.
See log file attached.

Thanks to analyse it
[atlassian-bitbucket.log](https://github.com/reconquest/atlassian-external-hooks/files/3110542/atlassian-bitbucket.log)

Sami

**Comment by kovetskiy** [comment]
Hi, @PenelopeSam 

what version of bitbucket are you running?

**Comment by PenelopeSam** [comment]
Hi
I'm running : Atlassian Bitbucket v6.2.0.

**Comment by kovetskiy** [comment]
@PenelopeSam yes, the plugin is incompatible with Bitbucket >6.0, but a few weeks ago Atlassian has released 6.2.0 that introduced a few features and it made our plugin compatible again, but it required full plugin rework. Currently, the plugin is working (on testing stages) and we are working on migrations from old hooks to new hooks. We expect to have the release in a week, if you want to be our early adopter, please let me know via `we@reconquest.io` and I'll share it.

**Comment by seletskiy** [comment]
Closing since plugin is compatible with BB 6.2.0+
