### ISSUE TITLE
Commit via GUI does not trigger external hook

### ISSUE THREAD

**Issue by urol** [reconquest/atlassian-external-hooks#94]
Bitbucket: 6.4.0
external-hooks-6.3.1-1
No entry in log and no triggering takes place when commit is done in the browser.
It works for PR from the browser as well as for commits/PR's via git push.

**Comment by kovetskiy** [comment]
Hi!

Thanks for the bug report, we've rolled new release that fixes that behavior:
Server installation: https://marketplace.atlassian.com/apps/1211631/external-hooks/version-history#b6272
DataCenter installation: https://marketplace.atlassian.com/apps/1211631/external-hooks/version-history#b6282

Or just upgrade your plugin through Manage Apps tab in admin panel, the new version is 6.3.2-1.

Related commit: https://github.com/reconquest/atlassian-external-hooks/commit/3cd9d1377a8e43f1ba7af9ae5d17f21b08971c55

**Comment by urol** [comment]
Thanks for the fast fix. Works well.
