### ISSUE TITLE
After upgrading to Bitbucket Data Center 6.4, pre-receive hook does not work

### ISSUE THREAD

**Issue by ddecul** [reconquest/atlassian-external-hooks#96]
I just upgraded to Bitbucket Data Center 6.4 and since the upgrade, the External hook has not been working correctly.  With the hook disabled, it is still triggering a pre-receive commit script.  When the hook is enabled, it is firing the pre-receive commit twice.

**Comment by seletskiy** [comment]
@ddecul 
Hi!

Just reaching you out to tell that we're trying to reproduce issue on our test environment.

**Comment by kovetskiy** [comment]
@ddecul Hi, what version did you use before 6.4? I just tried upgrading from 6.2.0 to 6.4.0 and it works as expected.

Also, could you send us logs of bitbucket-server during startup on our email we@reconquest.io? Logs should not contain any sensitive information with `WARN` log level.

**Comment by ddecul** [comment]
I was using 5.8.3.

**Comment by ddecul** [comment]
I was on a call with Atlassian and the problem was not related to the plug-in. For some reason, I had to reinstall Perl and after that the error went away.

**Comment by seletskiy** [comment]
@ddecul this is really strange! Thanks for the feedback.
